### ISSUE TITLE
Add an AFCH preference to turn off auto watchlisting

### ISSUE THREAD

**Issue by NovemLinguae** [wikimedia-gadgets/afc-helper#298]
Reported by Significa liberdade and Vanderwaalforces in Discord

Steps to reproduce
- while logged out, create a draft with the template {{AfC submission}}. this will put it in a submitted state
- log in and visit the draft
- accept it

What happens?
- Article and article talk are watchlisted
- User talk message is not watchlisted

What should happen instead?
- Should add an AFCH preference to turn off auto watchlisting. If that preference is selected, then article and article talk do not get watchlisted
<img width="483" alt="image" src="https://github.com/wikimedia-gadgets/afc-helper/assets/79697282/9b877392-a702-4bb7-be7e-8ce4623a9876">

Notes
- This may be caused by the user's Special:Preferences. If so, the fix may be to read AFCH's watchlist preference, and if turned off, do an API query right after the accept to unwatchlist the two pages.
<img width="425" alt="image" src="https://github.com/wikimedia-gadgets/afc-helper/assets/79697282/1f285a1d-a3ca-40dd-be48-47212edc3079">

**Comment by MPGuy2824** [comment]
Setting the correct preference for the _watchlist_ param while calling the edit api (https://www.mediawiki.org/wiki/API:Edit) should be enough.

**Comment by zanhecht** [comment]
I submitted pull request #300 for a patch which adds a "Do not add pages to watchlist" preference. When that preference is checked, it adds "watchlist: 'nochange'" to all the edit and move requests made by the script. It also makes it so the script never adds [[Wikipedia:Articles for creation/recent]] to the watchlist, since there is no value in doing so each time a draft is approved.
