### ISSUE TITLE
Add {{db-g11}} option for submissions declined as advertising

### ISSUE THREAD

**Issue by MER-C** [wikimedia-gadgets/afc-helper#92]
Irredeemably promotional submissions should be deleted to discourage tendentious resubmission. See 

https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Articles_for_creation/Decline_comments_workshop#adv

**Comment by CurbSafeCharmer** [comment]
I support this suggestion. It could also appear on the reject screen, perhaps?

**Comment by primefac** [comment]
I'm on the fence, but my initial thought is that it would over-promote G11 nominations. I do realise that drafts are not G11-proof, but they _are_ allowed to be more "blatantly promotional" than what's in the article space, since they're a work in progress.

**Comment by kzhovn** [comment]
I've wanted this for a while and would be up for taking this issue - could it be possible to add a _reject_ reason that's essentially G11? Something like "This submission [[WP:PROMOTION|appears to be an advertisement]] rather than an entry in an encyclopedia." would be about as brief as the other reject messages. 

The current decline message suggests that the author should improve the draft, which makes it feel rather cruel to immediately G11 it.

**Comment by NovemLinguae** [comment]
When a user picks cv (copyvio) as the decline or reject reason, it adds a little checkbox that says "Nominate the submission for speedy deletion". Could probably search for that in the repository and just tweak the existing code a bit, so that it 1) also shows up for decline reason adv (advertising), and 2) places {{Db-g11}} instead of {{Db-g12}}

Thinking more broadly, could add this feature to decline reason van (vandalism) and have it add {{Db-g3}}, but I should probably create another ticket for that.

![2022-04-21_211040](https://user-images.githubusercontent.com/79697282/164599482-9bce7d2f-802d-4281-816f-5e847ce351ea.png)

**Comment by kzhovn** [comment]
Yeah, the modification from G11 seems straightforward (famous last words), I was just wondering if it might make sense to instead add a separate "reject as adv" option and add the "tag as G11" textbox there.

It looks like a db-g3 and db-g10 issue already exists #91.

**Comment by primefac** [comment]
I have this vague recollection that we decided a while ago that defaulting to G11 as an option for declines or rejects was not something we wanted to do, but I haven't yet searched through the archives to find it.

**Comment by primefac** [comment]
Well... ignore my last, the most recent discussion from 2020 seems to indicate this would be a good idea... https://en.wikipedia.org/wiki/Wikipedia_talk:WikiProject_Articles_for_creation/Archive_41#ACFH_promotion%2Fadvert_needs_G11_option

**Comment by NovemLinguae** [comment]
Sorry, have to decline this one. The most recent discussion at WT:AFC did not achieve consensus for this feature.

https://en.wikipedia.org/wiki/Wikipedia_talk:WikiProject_Articles_for_creation#Have_AFCH_allow_quick_CSD_tagging%3F
